docs/workflow.md
Our docs should use example.com or similar domains for examples wherever possible.
=> Use (in)valid example domains

internal/service/operator.go, internal/service/service.go
Fixes #34
Added a check in operator service to detect undefined driver, however, it is the right thing to just bubble that error out at that place.  Placed a defer/recover in `serviceLoop` to make sure the all local process errors are recovered and won't cause loop and daemon to die.
=> fix(service): issue #34 daemon crashing when operator call undefined driver

internal/service/service.go, internal/service/service_test.go
Adding recover for all child go routines in service to avoid daemon crashing.  Also adding a test for this.
Fixes #34
=> fix(service): adding recover for all child go routines

internal/service/engine.go
When fetching data from messages for interpolation purpose, event message has data and some meta info, so the data is in a field `Payload.data`. For other type of messages, the whole `Payload` field is the data. The `data` type workflow returns a pseudo message without `Channel` and `Subject`, the workflow engine treated it as an event message so only using data under `Payload.data` field. With this fix, the `data` type workflow can use the whole `Payload` to return data.
N/A
=> fix(workflow): only event message payload in data

deployments/helm/honeydipper/README.md, deployments/helm/honeydipper/templates/webhook-service.yaml, deployments/helm/honeydipper/values.yaml
Adding a variable to the helm chart so that the nodePort for the service can be customized.  This is useful in some cases when you want a static nodePort for your service to roll your own load balancer solutions etc.
N/A
=> feat(helm): make service nodePort customizable

build/docker/Dockerfile
* Multi-stage build will result in a much smaller runtime container.
* Update labels.
```
lana~% docker run 36544890d454                                            
22:15:57.498 daemon.initEnv ▶ CRIT 001 REPO environment variable is required to bootstrap honeydipper
22:15:57.498 daemon.initEnv ▶ CRIT 001 REPO environment variable is required to bootstrap honeydipper
lana~% docker run 36544890d454 -h
./honeydipper [ -h ] service1 service2 ...
Supported services include engie, receiver.
Note: REPO environment variable is required to specify the bootstrap config.
lana~% docker run --entrypoint /bin/ls 36544890d454 
datadog-emitter
dummy
gcloud-dataflow
gcloud-gke
gcloud-kms
honeydipper
kubernetes
redispubsub
redisqueue
web
webhook
```
- Fixes #56
=> chore: Update Dockerfile and move to multi-stage build

build/docker/Dockerfile, drivers/cmd/gcloud-kms/main.go
Ensure the images we built has `ca-certificates` to avoid grpc x509 unknown CA issue.
Fixes #72
=> fix(grpc): ensure CA certificates available for grpc TLS

.gitignore, Gopkg.lock, drivers/cmd/web/main.go, drivers/cmd/web/main_test.go
* Add basic test cases for (outgoing) web driver
* Return an error label if response code is >= 4XX
Fixes #69
=> fix(drivers): Return error on >= 4xx response and add tests

docs/INSTALL.md, internal/config/gitssh.go
Switch `HONEY_` prefix for env vars to `DIPPER_`
Not sure if we should categorize this as refactor or make this a breaking change. Will obviously have to coordinate with other places this change is needed.
N/A
=> chore: Switch HONEY_ prefix for env vars to DIPPER_

docs/interpolation.md, docs/workflow.md
The markdown formatted documents are not showing properly when using github pages.  This is because the jekyll templating engine used by github pages tries to expand the double curly braces in the sample code snippets.  We will use the jekyll `raw` block (wrapped inside html comments) to wrap around the code snippets to bypass the expansion.
N/A
=> docs(jekyll): bypass jekyll expanding double curly braces

docs/interpolation.md
Github pages throwing errors complaining about this loose brace. Wrapping this with raw block should fix it.
N/A
=> docs(jekyll): wrapping some loose double curly braces

build/docker/Dockerfile
Add git to final Docker build
```
Successfully built 4807236d3292
[...]
% docker run --entrypoint /bin/sh -it 4807236d3292 
/opt/honeydipper/drivers/builtin # git --version
git version 2.20.1
```
Fixes #84
=> fix: Install git in Docker image

drivers/cmd/web/main.go
Logic error in the web driver where the body is not closed unless there is a error. This PR should fix this.
N/A
=> bug(web): response was not closed causing memory leak

internal/service/engine.go, internal/service/engine_test.go, internal/service/main_test.go, internal/service/operator.go
Bug: its possible for workflow to search for data in nil Payload
Fix: before building new packet, build an empty Payload, so data search that occurs in an empty Payload has graceful error/failure
Fixes #70
=> fix(daemon): Don’t panic when Payload is nil

drivers/cmd/web/main.go, drivers/cmd/web/main_test.go
json Payload uses interface to support top level array
Fixes #92
=> fix(web): json Payload use interface to support top level array

drivers/cmd/webhook/main.go, drivers/cmd/webhook/main_test.go
Update extractEventData function in driver/cmd/webhook to get host and remoteAddr from request
Fixes #85
=> feat(driver) #85: extract host and remoteAddr from eventData

internal/config/schema.go, internal/service/engine.go, internal/service/engine_test.go, internal/service/operator.go, internal/service/service.go, internal/service/service_test.go
This PR adds export feature to `Trigger`, `Function` and `Workflow` as described in issue #99. It still maintains backward compatibility for now.  The `wfdata` is still available in interpolation, the `Data` field of `Workflow` remains. But, we can start using `ctx` and migrating all `wfdata` to `ctx`.
Fixes #99 partially
=> feat(engine): function/event data export into context

semantic.yml
- Probot configuration for semantic-release
This is one style we could allow; otherwise, we could force on PR titles only, and force squash-merging.
n/a
=> ci: Probot configuration for semantic-release

.circleci/config.yml, Gopkg.lock, Gopkg.toml, build/docker/Dockerfile, drivers/cmd/gcloud-dataflow/main.go, drivers/cmd/gcloud-gke/main.go
Upgrading the go version to 1.12.9 along with dependency updates.  This should address the CVE-2019-9512 an CVE-2015-9514.
The first 4 commits were cherry-picked from DipperCL branch. To avoid later issues when rebasing and merging from DippeCL branch, we should probably not squash the changes.
Fixes #112
=> fix(security): upgrade to 1.12.9 to fix CVE-2019-9512 and CVE-2019-9514

build/docker/Dockerfile
The build process on codefresh.io is limited to use only 1G memory.  The `dep ensure` might be consuming too much memory.  By adding a `-vendor-only`, we are reducing the complexity and hopefully reduce the memory demand.
=> fix: dep ensure ran out of memory when building @ codefresh.io

build/docker/Dockerfile
The build pipeline is limited to only 1G ram. Since upgrading to go1.12.9, the `go install` commands seems consuming more RAM and causing the build process to be killed. Earlier PR #118 was trying to reduce the memory footprint of the `dep ensure` command which was not addressing the right issue.
This PR reverts #118, and also adds option for the build process to take parameters from the build pipeline to adjust how the build is made.  By specifying `GOGC=50`, and `GOINSTALLOPTS="-p 1"` in the pipeline, the build process is now able complete.  
n/a
=> chore(build): go install ran into oom @ codefresh.io

docs/INSTALL.md, docs/documenting.md
Updating the documents where `DipperCL-rc?` was mentioned to use `1.0.0`.
=> docs: update docs to refer to 1.0.0 instead of release candidates

docs/howtos/setup_local.md
updating init config for setup_local guide
The configurations for setup_local guide has been outdated and needs to be updated. This will fix the problem of people can't start honeydipper
=> docs: updating init config for setup_local guide

internal/workflow/continue.go, internal/workflow/session_hook_test.go
When an error happens in the completion hook (on_success, on_error, on_failure or on_exit), the exiting logic fails to clear the `currentHook` flag so the session never executes `complete`. This causes the session to stay in memory forever.
#130
=> fix: error in completion hook causing run away workflow sessions

internal/workflow/session.go, pkg/dipper/rpc.go
Fixes #121 
- Currently, we are reading the Result map by directly accessing it, We switched it to use IDMapGet in order to utilize the Mutex Lock to make this operation concurrently safe
- Correct typo in the context missing panic message in our session
=> fix: uses concurrent safe reading function while reading Result map

internal/workflow/continue.go
Currently, the complete function of Session struct is reading the sessions map by directly accessing it. We switch this to use IDMapGet to utilize the Mutex lock to make this operation concurrently safe
Fixes #142
=> fix: safe reading function for sessions map

renovate.json
* Code dependency updates as `fix(deps)` vs `chore(deps)`
n/a
=> chore: Dependency updates should be type fix

renovate.json
* For most of the Go deps we want to update, the type seems to be set to 'require' vs. 'dependencies'.
n/a
=> chore: Use 'require' as Renovate deptype

.circleci/config.yml, .releaserc, build/docker/Dockerfile, go.mod, go.sum, renovate.json
* chore: Dependency updates should be type fix (#148)
* chore(deps): update golang.org/x/oauth2 commit hash to bf48bf1 (#149)
* chore(deps): update alpine docker tag to v3.11 (#152)
* fix(deps): update google.golang.org/genproto commit hash to 58ce757 (#150)
* ci: Remove extraneous assets (#151)
* fix(deps): update golang.org/x/crypto commit hash to 69ecbb4 (#147)
* chore: Use 'require' as Renovate deptype (#154)
* fix(deps): update github.com/logrusorgru/aurora commit hash to e9ef32d (#146)
* fix(deps): Update to go 1.13.6 (#156)
=> chore(release): release

internal/config/config.go, internal/config/config_test.go, pkg/dipper/interpolation.go, pkg/dipper/interpolation_test.go, pkg/dipper/mapUtils_test.go
* Parsing regex pattern in `unless_match` workflow field
* Ensuring dollar interpolation not omit the commas in default value
Fixes #187 
Fixes #188
=> fix(config): regex patterns in unless_match and dollar interpolation default val with comma

renovate.json
I think releasing every two weeks is a reasonable schedule, so we should adjust renovate to also run every two weeks. This should make renovate PRs less noisy.
N/A
=> chore: adjust renovatebot run frequency

internal/service/operator.go
* stop functions from inherting retry and backoff_ms labels from other calls.
Fixes #181
=> fix: stop passing backoff_ms, retry labels

drivers/cmd/gcloud-dataflow/main.go, drivers/cmd/gcloud-gke/main.go, drivers/cmd/gcloud-kms/main.go, drivers/cmd/kubernetes/main.go, internal/service/operator.go, pkg/dipper/commandHandler.go, pkg/dipper/commandHandler_test.go, pkg/dipper/driver.go
* enforcing the function variable timeout on driver framework level
* change the existing drivers to use this timeout settings for the long ops
* allowing setting API level timeout from driver config
* the default function level timeout is set to 30s
* the default api level timeout is set to 10s
* the default function level backoff period is set to 1s
Fixes #229
=> feat(cmd): enforcing variable timeout for functions

internal/workflow/condition.go, internal/workflow/condition_test.go
While testing the `deleteJob` function of `kubernetes` driver, I found out that the `until` condition check doesn't work.  It turns out that the undefined context variable presents as `<no value>` after interpolation. But, the condition check in the workflow engine doesn't recognize it and consider it as truey value.  This commit should fix it.
=> fix(workflow): truthy condition check should recognize <no value>

drivers/cmd/gcloud-dataflow/main.go, drivers/cmd/kubernetes/main.go, pkg/dipper/commandHandler.go, pkg/dipper/commandHandler_test.go
* Find and fix all functions with faulty `break` statement
* Avoid reusing `rchan` after it is closed
* passing a separate `Message` for each attempt in retry 
* Added a testcase for dealing with **rogue** functions
Fixes #250
=> fix(drivers): driver panic due to closed channel during retry

cmd/honeydipper/configcheck.go, cmd/honeydipper/configcheck_test.go
* Use double quotes instead of backticks around strings in configcheck output
* Slight rewording / reformatting on headings
=> refactor(configcheck): update error formatting

cmd/honeydipper/configcheck.go, cmd/honeydipper/configcheck_test.go
Context errors weren't causing configcheck to exit with a non-0 exit code
* Return 1 on context error
* Add test coverage for runConfigCheck() return code
Fixes #255
=> fix(configcheck): exit non-zero on context errors

internal/config/function_export.go, internal/config/function_export_test.go, internal/workflow/continue.go, pkg/dipper/mapUtils.go, pkg/dipper/mapUtils_test.go
* rewrite the `ExportFunctionContext` func to ensure the parent/subsystem data are arranged
* allow merging and deep copying nil
* more tests for the the changes
Fixes #269
=> fix(config): function export should arrange parent subsystem data properly

drivers/cmd/kubernetes/main.go
When deleting k8s jobs, the succeeded pods were orphan'ed and left for the k8s cluster to GC them until a threshold is reached. With this change, the pods will be deleted as well.
Fixes #280
=> fix(k8s): cascading deletion of pods when deleting jobs

build/docker/Dockerfile
The build process is failing at codefresh.io due to memory consumption over 1G limit. Hopefully splitting the build steps can help.
=> build(docker): split the build for lower memory consumption

pkg/dipper/mapUtils.go, pkg/dipper/mapUtils_test.go
* Make sure `nil` won't cause any errors when processing merge modifier
* Add tests
N/A
=> fix(dipper): map modifier handle nil value gracefully

drivers/cmd/gcloud-dataflow/main.go, drivers/cmd/kubernetes/main.go, pkg/dipper/errorHandling.go
The `createJob` function will try to look for the job with the same name or uniq identifier,
and if found, will return it instead of creating a new one. This will allow the call to be
retried if the call was timed out waiting for API return.
k8s job template needs to have a field `honeydipper-unique-identifier` to specify the uniq identifier.
Dataflow jobs will use their name as the unique identifier.
N/A
The two commits are cherry picked from the `CH-api5` branch. I intend to release them sooner. Let's do `rebase merge` so it won't conflict with the `CH-api5` brach.
=> feat(drivers): spanner and k8s createJob allows retry

build/docker/Dockerfile
Still reaching memory limit at codefresh.io build step. Breaking down
the steps seems keeping the memory utilization below 700MB.
N/A
=> ci: docker build break down steps to save memory

cmd/honeydipper/configcheck.go, drivers/cmd/auth-simple/main.go, go.mod, go.sum, internal/api/def.go, internal/api/main_test.go, internal/api/request.go, internal/api/request_test.go, internal/api/response.go, internal/api/response_test.go, internal/api/store.go, internal/api/test_fixtures/TypeAllAPI.yaml, internal/api/test_fixtures/TypeAllAPITimeout.yaml, internal/api/test_fixtures/TypeFirstAPI.yaml, internal/api/test_fixtures/TypeMatchAPI.yaml, internal/api/test_fixtures/TypeMatchAPILongRequest.yaml, internal/api/test_fixtures/TypeMatchAPINoMatch.yaml, internal/api/test_fixtures/UnauthorizedAPI.yaml, internal/api/test_fixtures/common.yaml, internal/config/repo.go
* switch authorization to use casbin library
* move request_test cases from code to yamls in fixtures
* adjust auth_simple driver to return simple subject
* run tests against the auth rules using `configcheck`
N/A
=> refactor(api): use casbin authorization library

go.sum, internal/api/request_test.go, pkg/dipper/driver.go
The `api_timeout` is actually under `data` in driver data structure.
The test code injects the api ack/reply messages as soon as the outgoing request is sent. However
the old way signalling seems unreliable. It sometimes takes longer than 10ms between closing a channel and
receiving a zero value from the channel on the other end. The new code just put the starting of
message injection and completion of message sending together so no signalling is needed. This
should avoid the timing issue.
N/A
=> fix(pkg): driver api_timeout under data

internal/workflow/continue.go, internal/workflow/main_test.go, internal/workflow/session.go, internal/workflow/store.go
reverting commit cffb8b3f3fb075be0001f7a6271f427d08617f93
This change although simplifies the process of exports, but it
does not handle layered exports well, and breaks exports with
appending merge modifier.
N/A
=> fix(workflow): revert simplify export

drivers/cmd/kubernetes/main.go, pkg/dipper/commandHandler.go
* The `Close` statement in `getJobLog` was moved to the wrong branch of the `if`. This causes
invalid point exceptions for all k8s jobs that failed in `initContainers`.
* Use `errors.Wrap` in `commandHandler` to show the stack trace in log for
easier troubleshooting.
N/A
=> fix(drivers): k8s getJobLog misplaced Close statement

.circleci/config.yml
golangci-lint already runs golint, gofmt, and gofumpt
https://golangci-lint.run/usage/linters/
so the existing "lint" step that checked formatting and ran golint should be unnecessary / redundant.
=> ci: remove redundant formatting and golint checks

.circleci/config.yml, .golangci.yml, cmd/honeydipper/configcheck_test.go, internal/api/request.go, internal/api/request_test.go, internal/api/response_test.go, internal/api/store.go, internal/config/config.go, internal/config/file_reference.go, internal/driver/builtin.go, internal/driver/builtin_test.go, internal/driver/driver.go, internal/driver/driver_test.go, internal/service/operator.go, internal/service/service.go, internal/service/service_test.go, internal/workflow/session.go, pkg/dipper/comm.go, pkg/dipper/commandHandler.go, pkg/dipper/errorHandling.go, pkg/dipper/interpolation.go, pkg/dipper/mapUtils.go, pkg/dipper/rpc.go
- update golang-ci in Circlel config to latest
- update pinned golangci-lint-version to match version in CI
- wrap errors
- use builtin errors (refactor by @Charles546)
- switch from a = a * b to a *= b and i = i + 1 to i++
- disable exhaustivestruct
- other minor formatting / stylle changes
Closes #336
=> refactor: lint and style updates

go.mod, go.sum, pkg/dipper/logging.go
- move away from deprecated `golang.org/x/crypto/ssh/terminal` to `golang.org/x/term` in logging package
- Update golang.org/x/crypto => v0.0.0-20200622213623-75b288015ac9
Closes #344
=> fix(logging): switch to golang.org/x/term

internal/api/test_fixtures/TypeAllAPI.yaml, internal/api/test_fixtures/TypeFirstAPI.yaml
Keeps getting timeout in Circle test, it is unpredictable
how long it takes for a go `channel` to communicate between
two go routines. Using a longer timeout to avoid test
failures.
N/A
=> test(api): longer timeout in api test

internal/api/test_fixtures/TypeAllAPITimeout.yaml
This test also needs a longer `ackTimeout`.
N/A
=> test(api): timeout for TypeAllAPITimeout test

internal/api/response_test.go
Similar to request tests issue in #351 and #352, response
tests also have the timing issues, probably due to that Circle
steals too much CPU cycles from the container. Increasing the
timeout should make it less likely, if not completely avoid
the timing issues.
N/A
=> test(api): response test timing issue

docs/developer.md, go.sum, internal/service/operator.go
`wfdata` has been deprecated, use `ctx` instead.
N/A
=> fix(internal): remove wfdata interpolation

internal/workflow/continue.go, internal/workflow/session.go, internal/workflow/store.go
In mutli-threaded workflows, multiple child workflows might complete
at the same time, and might try merging their exports at the same time.
To avoid concurrent map write, we use a lock to ensure only one thread
can run `mergeContext`
Fixes #356
=> fix(workflow): avoid concurrent map write in mergeContext

cmd/honeydipper/integration_test.go, cmd/honeydipper/main.go, internal/config/config.go, internal/config/config_stage_test.go, internal/config/config_test.go, internal/config/function_export_test.go, internal/driver/driver_test.go, internal/service/api.go, internal/service/engine.go, internal/service/operator.go, internal/service/service.go, internal/service/service_test.go, pkg/dipper/mapUtils.go, pkg/dipper/sync.go
The concurrent map writes are usually caused by updating to
the configuration when the services decrypt some piece of
data, or a regexp is parsed.
This commit changes how the configuration handles the updating
of the configs. Instead of, delaying the decryption and regexp
parsing to later time, the config module will take care of them
at the startup of the services.
The config process will be divided into multiple stages, and
all the services will be synchronized to use the configuration
according to the stages. Also introduced a `RawData` to holds
the raw data for use in rollback and re-decrypt, if necessary.
The configuration becomes readonly to services.
* Add stages and the synchronizing variables to config
* Put decryption and regexp parsing into stages
* Remove scattered calls for …
=> fix(config): avoid concurrent map write in config

.codefresh/honeydipper-sphinx.yml
* Use `main` branch for `honeydipper-sphinx` building
* Use `ssh-keyscan` to avoid ignoring host key check
* Correct the diff and commit statement
N/A
=> chore(codefresh): migrate to main for honeydipper-sphinx

cmd/honeydipper/configcheck.go, cmd/honeydipper/configcheck_test.go, cmd/honeydipper/docgen.go, cmd/honeydipper/main.go, cmd/honeydipper/main_test.go, go.sum, internal/config/config.go, pkg/dipper/sync.go
In PR #358, we altered how `config` was loaded, this breaks
the `docgen` and `configcheck`. We need to use `Staged` dataset
instead of the live one. Also, need to advance the config to
discovered stage to ensure all systems are extended.
Also, there is a bug in the `AdvanceStage` method, that the
`WaitGroup.Wait` may panic if previous call to `Done` paniced.
We should wrap it.
N/A
=> fix(config): Wrapping WaitGroup.Wait in AdvanceStage

cmd/honeydipper/integration_test.go, cmd/honeydipper/test_fixtures/bootstrap/daemon.yaml, cmd/honeydipper/test_fixtures/bootstrap/drivers.yaml, internal/service/api.go
The `APIFeatures` method is in charge of discovering what drivers to
load for api service. The old way is to use dataset in `APICfg`.  With
the new staged config loading method since version 2.1.3, it doesnt work
any more because the `APICfg` is not initialized during discovery. It is
supposed to use the dataset object passed in as parameters.
Also, added some api related tests in integration test,
N/A
=> fix(services): api service discovery using staged dataset

.golangci.yml
golangci-lint deprecated enable-all, so switching to enabling specific linters
=> ci: switch to explicit enables

pkg/dipper/driver.go
A `chan` needs to be initialized before first use. We are missing the
initialization part for `ReadySignal`, but for some reason `go` does not
check for it, and allow you to send to or receive from `0x0`, and
potentially corrupting memmory.
The `ReadySignal` is used for signalling the readiness of the
configuration received from the `daemon`. Originally, it was considered
to be optional, since not all driver requires a configuration from
`daemon`. So, a timeout of one second was in place to forcefully start
the driver even without the signal.  I am changing this to be mandatory
so it can be a little easier sequencing the lifecycle, and avoid race
conditions. The `Driver` is receiving an empty configuration from
`daemon` even if no configuation is needed.
N/A
=> fix(dipper): driver ReadySignal chan initialization

Makefile, drivers/cmd/gcloud-secret/main.go, drivers/cmd/gcloud-secret/main_test.go, internal/service/service.go, pkg/dipper/encryption.go, pkg/dipper/encryption_test.go
The new driver should provide the capability to fetch secrets from
google secret manager.
The daemon code is updated to support passing non-base64 string to the
driver for lookup instead of decryption.
N/A
=> feat(drivers): fetch secrets from google secret manager

internal/config/gitssh.go
Preivously, the daemon tries using the ssh-agent socket first, if one is
present. It is impossible to override it with the `DIPPER_SSH_KEY`
environment variable. This will correct the order and make it possible.
N/A
=> fix: re-ordering the git SSH auth options

drivers/pkg/redisclient/redisclient.go
When testing in non-local environment, such as `docker-compose`, we need a
way to override the redis config through environment variable other than using
`127.0.0.1:6379`.
N/A
=> feat(driver): load redis option from env variable

drivers/cmd/web/main.go, drivers/cmd/web/main_test.go
Query parameters can be repeated to represent an array. One use case
is when making API calls to pagerduty. For some of the filters, the
parameter accepts an array.
N/A
=> feat(drivers): web request support multiple value query variables

Makefile, drivers/cmd/datadog-emitter/main.go, drivers/cmd/datadog-emitter/main_test.go, drivers/cmd/datadog-emitter/statsd.go, internal/service/operator.go
Previously, the driver only allow RPC calls. Now, we can also use
this feature through functions in yaml.
Also, add tests to improve test coverage.
=> feat(drivers): datadog-emitter allow functions

drivers/cmd/web/main.go, pkg/dipper/web.go
The drivers should not rely on an exact match of `application/json` content type.
N/A
=> fix(drivers): web and webhook recognize more json content types

.circleci/config.yml
semantic-release is failing due to requiring a node version upgrade.
N/A
=> chore(ci): update image for semantic-release

.circleci/config.yml, .github/semantic.yml, .github/workflows/check-semantic-commits.yml, build/docker/Dockerfile, build/docker/Dockerfile-dev
- Update to latest 1.17 version of go in Docker and CI
- Update to Alpine 3.15
- Update golangci-lint to v1.43
- Run go fmt on test files in CI
- Update node for semantic-release step to 16
=> build: go version and CI updates

internal/api/store.go, internal/api/test_fixtures/TypeMatchAPI.yaml, internal/api/test_fixtures/TypeMatchAPILongRequest.yaml
When building an API request, the default timeout should match the store
configured `writeTimeout`. When using the constant value as default, it causes
the API has a longer timeout, and confuses the store yielding 202s instead of
500 timeouts.
Also include a test fix:
This is the only test seems still constantly timing out for the last couple of
months. Increasing the actTimeout should improve this as it did for the type all test.
The better resource class since last PR also helps.
N/A
=> fix: API default timeout use store writeTimeout

pkg/dipper/certs_test.go
`x509.CertPool` no longer supports `Subjects` methond in go1.18. We have
no way of checking if the cert pool is populated or not, or if a cert is
present in the pool or not. Simplifying the test for now, maybe we can
add better test in future.
#474
=> test: x509.CertPool no longer supports Subjects

.github/workflows/check-semantic-commits.yml, cmd/honeydipper/integration_test.go, drivers/cmd/webhook/main.go, internal/config/config.go, internal/config/gitssh.go, internal/driver/schema.go, internal/service/api.go, internal/service/engine.go, internal/service/operator.go, internal/service/receiver.go, internal/service/service.go, pkg/dipper/driver.go, pkg/dipper/sync.go, pkg/dipper/sync_test.go
Upon forceful reload, gracefully stop all drivers before shutdown the
daemon process. Adding a stage in config named `Drained`.
This is useful when we migrate the work from one node to another to allow daemon restarting.
N/A
=> feat(core): graceful shutdown by draining drivers

.circleci/config.yml
Looks like semantic release now requires node 18 and above.
https://app.circleci.com/pipelines/github/honeydipper/honeydipper/2810/workflows/5d7c03b6-9d4a-479c-a5fb-4469d6550a24/jobs/8584
=> ci: upgrade node for semantic release

.circleci/config.yml
semantic release still failing because the circleci/node images are superseded by cimg/node images.
https://app.circleci.com/pipelines/github/honeydipper/honeydipper/2815/workflows/b8707461-32cc-4127-a22d-ae5a7bc83a71/jobs/8612
=> ci: use correct node image for ci

internal/service/engine.go, internal/service/service.go, internal/workflow/condition_test.go, internal/workflow/execute.go, internal/workflow/mock_workflow/store.go, internal/workflow/session_context_test.go, internal/workflow/session_faulttolerant_test.go, internal/workflow/session_hook_test.go, internal/workflow/session_parallel_test.go, internal/workflow/store.go, internal/workflow/store_session_test.go
Prepend the daemonID in front of the resume_token makes it globally unique. This
avoids token collision, and ensures the right session gets resumed, when called.
N/A
=> fix(core): resume_token should be unique among cluster members

internal/config/repo.go, pkg/dipper/interpolation.go, pkg/dipper/interpolation_test.go
It is useful to return typed or structured data from templates. We can avoid parsing yaml in the string to get typed data, such as boolean, int, map or list.
N/A
=> feat(core): allow return typed data from go template

pkg/dipper/commandHandler.go
commandHandler uses the source msg labels to create the return msg, so if the labels are updated in the function call, the return message will have dirty labels. This causes function returns get send to a wrong recipient in cluster environments. An example is when a workflow calls broadcast method of the redispubsub driver, the source labels were reused to send the broadcast message, and `from` label was updated to local node IP. The function never returns to the caller. By making a copy in the commandHandler, this can be avoid.
=> fix: commandHandler protecting the return labels

internal/config/schema.go, internal/workflow/continue.go, internal/workflow/session.go, internal/workflow/session_context_test.go
Export on error was previously ignored. However, it is found
to be important to be able to use export on error to construct
meaningful data and messages for subsequential operations. This
should make it possible to do that.
add test for export and export_on_error
=> feat: allow export on error

drivers/cmd/web/main.go
The web driver does not create a request body for a PATCH request, which fails on API calls using PATCH method.
=> fix: patch method require body in the request

.github/workflows/codeql-analysis.yml
Update deprecated v1 action to v2
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
- Remove unused checkout of HEAD~2
- Remove some comments
- Update branch name
=> ci: update codeql workflow

internal/workflow/continue.go, internal/workflow/session_context_test.go, pkg/dipper/errorHandling.go, pkg/dipper/errorHandling_test.go
Without the protection, the export failure of the workflow will cause the workflow to get stuck in memory, can not be cleaned up.
=> fix(core): workflow export failure protection

internal/config/file_reference.go
Since we are using full path in loadFile, the file reference path can now be found without using the c.root.
=> fix: file reference path correction

go.mod, go.sum, internal/workflow/session.go
Ensure each context is only loaded once, and `*` section is loaded only
during the initial loading of the context.
N/A
=> fix: load each context only once

internal/workflow/continue.go, pkg/dipper/security.go, pkg/dipper/security_test.go
The label value could be the complete output of a job. Better to shrink it before showing in the logs
=> feat: truncate the labels before displaying in logs

drivers/cmd/web/token.go, drivers/cmd/web/token_test.go, go.mod
* add headers to the access_token request
* longest allowed token expiration time is 10 min
* token_sources should be under data in driver.Options
=> fix: correct web driver token_sources missing headers

internal/config/schema.go, internal/daemon/daemon.go, internal/workflow/execute.go, internal/workflow/session.go, internal/workflow/store_test.go
Making a child workflow independent so it can show up during get events API call. Also the child workflow will no longer followed by the parent workflow hooks.
=> feat: detach a child workflow to make it independent

internal/workflow/hooks.go, internal/workflow/session_hook_test.go
The hook execution return may override the parent workflow return causing following hook to receive wrong data. Making the hook execution in parallel avoids the problem and also make it faster.
=> fix: run hooks in parallel to avoid interference

.circleci/config.yml
Dockerizer can no longer be installed from apk
=> ci: install dockerize with wget

.circleci/config.yml
Previous release attempt failed because the latest version of semantic release require 18.17 up or 20.6.1 up. This should fix it.
=> ci: upgrade node version for semantic-release

internal/workflow/execute.go
The reusable Success message should be immutable, but it seems harder to maintain the immutability. There has been cases where the Success message was contaminated with failure message, which requires a restart to clear. Using a disposable success message seems safer and easier.
=> fix: not reusing success messages

.circleci/config.yml, .golangci.yml
Try to get golangci-lint to a passing baseline.
- Update golangci-lint to v1.59
- Update test file ignore regex
- Resolve deprecation warning from linter package renames, but comment out `mnd`, and `revive` for now - these can be re-enabled as separate PRs if desired, but create a number of warnings with the existing code.
Note: `depguard` was enabled in config, but doesn't seem to have a configured set of allowed dependencies, and as such, was failing.
It looks like things like the failures in #598 etc. have more to do with the large # of deps that are also getting updated there.
=> ci: update golangci-lint

drivers/cmd/kubernetes/main.go
=> fix: k8s job only fail if succeeded is 0

drivers/cmd/kubernetes/main.go
Previous PR #622 corrects the `waitForJob` return status for retry and succeeded jobs. However, `getJobLog` function still reports errors for that job. This should fix it.
=> fix: check k8s job status with conditions array

drivers/cmd/hd-driver-vault/main.go, internal/config/collapsed_trigger.go
secret lookup in hd-driver-vault should return byte array instead of a string.
Also, ensure all webhook events for systems with signatureSecrets are verified.
=> fix: secret lookup should return raw message with bytes
