honeydipper/honeydipper

- README.md
> docs: Update logo path

- internal/service/service.go
- internal/service/service_test.go
The way `service`(s) handle emitting is to see if there is an entry for it in `daemon.Emitters`, if present, use that (usually itself, since it implements the `Emitter` interface, might change in future) to emit. When emitter driver is removed or replaced, we need to remove the emitter (the service itself) from `daemon.Emitters` so it won't keep sending.  Previous, we are missing this in `removeUnusedFeatures`.
Also, when a driver is failed to load, or failed to replace, we are keeping a `driver.Runntime` object in the service so we can always account and emit the number of failed drivers.  However, we failed to ensure that the runtime object is at least a valid object (missing `Meta` info), causing panics at a few places that was not protected by `defer/recover`.  So, we made sure the …
> fix(service): detecting emitter absence and crashing and test

- build/docker/Dockerfile
* Update path in `Dockerfile`
* Add `--no-cache` to `apk` call
We can wait til some other changes happen to merge #54
n/a
> Update path in Dockerfile

- docs/INSTALL.md
- docs/README.md
- docs/configuration.md
- docs/developer.md
- docs/howtos/enable_encryption.md
- docs/howtos/reload_on_push.md
- docs/howtos/setup_local.md
* Changing the urls to use `honeydipper` repos.
* Improve some how to guides and installation guide
N/A
> docs(installation): migrating to honeydipper repo and more

- drivers/cmd/kubernetes/main.go
Instead of use the first replicaset in the list, we first find the revision information in the deployment annotations, then iterate through the replicasets to find the one with the same revision annotation.
Fix #61
> fix(kubernetes): recycling deployment by killing the correct replicaset

- .circleci/config.yml
Needs to clean up the CI config so we can test the build and deploy with tags.
N/A
> chore(ci): clean up CI config

- docs/README.md
Just make sure the links are still usable when docs are served with github pages, also adding badges and logo docs/README.md .
N/A
> docs(honeydiper.io): improve docs for honeydipper.io

- deployments/helm/honeydipper/Chart.yaml
- deployments/helm/honeydipper/README.md
- deployments/helm/honeydipper/templates/NOTES.txt
- deployments/helm/honeydipper/templates/daemon-deployment.yaml
- deployments/helm/honeydipper/test-values.yaml
- deployments/helm/honeydipper/test_fixtures/init.yaml
- deployments/helm/honeydipper/values.yaml
Enhancing the documents and chart files as per the [contribution guide](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#technical-requirements).
N/A
> chore(helm): preparing to submit to helm/charts

- docs/INSTALL.md
- docs/howtos/setup_local.md
- docs/interpolation.md
- docs/workflow.md
* Adjusting documents for installation/setup_local to match the helm/chart changes
* Skipping syntax highlighting for some yaml snippets for proper rendering in honeydipper.io
N/A
> docs(helm/charts): changing docs according to helm chart changes

- docs/INSTALL.md
- docs/configuration.md
- docs/developer.md
- docs/interpolation.md
Updates to wording, reflow some paragraphs @ 140 characters, and fix some minor typos.
N/A
> docs: Minor docs updates

- Gopkg.lock
- Gopkg.toml
- cmd/honeydipper/configcheck.go
- cmd/honeydipper/main.go
- docs/INSTALL.md
- docs/configuration.md
- docs/interpolation.md
- docs/workflow.md
- internal/config/config.go
- internal/config/repo.go
Adding a configcheck feature to Honeydipper daemon. 
Fixes #73
> feat(configcheck): run config check before publish configurations

- cmd/honeydipper/configcheck.go
Adding a few `wfdata` related checks
- `steps` are usually a list of work items that should not be merged, so should use `*steps` to avoid merging
- `work` are usually used in abstract workflow to represent an actual `workflow` structure
N/A
> feat(configcheck): a few checks related to wfdata

- docs/workflow.md
- internal/service/engine.go
- internal/service/engine_test.go
This enables timeout feature for suspended sessions.
N/A
> feat(suspend): suspended session can resume with a timeout

- drivers/cmd/webhook/main_test.go
The integration test failed intermittently in webhook main_test.go.  Seems a race condition somewhere in the test code. This PR is to add some assertion to guard against this type error, will barf with meaningful errors if happen again.
N/A
> fix(test): guarding against strange http errors in webhook test

- drivers/cmd/gcloud-dataflow/main.go
Adding the `updateJob` rawAction to gcloud dataflow driver, so we can drain jobs and update jobs.
Fixes #101
> feat(dataflow): added updateJob function for draining and cancelling job

- drivers/cmd/webhook/main.go
- internal/service/engine.go
- pkg/dipper/idmap.go
- pkg/dipper/idmap_test.go
A few fixes for 0.1.9.
Fixes #104 
Fixes #105
> fix(idmap): idmap thread safety fix and healthcheck fix

- drivers/cmd/gcloud-dataflow/main.go
- pkg/dipper/interpolation.go
Some enhancements are needed to make the new features in dataflow driver really useful.
* Instead of having a `listJob` function, a `findJobByName` function is more useful
* When using path interpolation in the function exports, should handle `nil` values more gracefully, meaning 1) having a way to allow nil, 2) supporting multiple paths where the first none nil is returned.
N/A
> feat(gcloud-dataflow): some enhancements for easier handling of dataflow jobs

- drivers/cmd/gcloud-pubsub/main.go
- drivers/cmd/gcloud-pubsub/main_test.go
This PR add a new driver for gcloud-pubsub, allow for honeydipper to add trigger for pubsub event
Fixes #89
> feat(driver): gcloud pubsub driver for subscriber

- docs/workflow.md
- Enhances docs for merging modifiers
n/a
> docs: enhance docs for merging modifiers

- docs/developer.md
- docs/interpolation.md
- docs/workflow.md
Have to remember to use `{% raw %}` to escape the `{{}}` in the document.
> docs: fixing jekyll compiling errors

- drivers/cmd/gcloud-dataflow/main.go
- drivers/cmd/kubernetes/main.go
- internal/workflow/execute.go
Switch "time out" to "timeout"
n/a
> refactor: Remove space from "time out"

- internal/service/operator.go
- pkg/dipper/commandHandler.go
- pkg/dipper/commandHandler_test.go
This adds the long expected retry/backoff logic to `function` and `rawAction` calls.
> feat: function and rawAction retry and backoff

- drivers/cmd/gcloud-pubsub/main.go
Pubsub driver was developed during the transition of version 0.x.x to 1.0.0.  One thing we missed is to use new format of the `collapsedEvents` when receiving options from daemon.  This patch fixes it.
N/A
> fix: pubsub driver supporting version 1.0.0 and later collapsedEvents format

- .circleci/config.yml
- .releaserc
- Add semantic release for automatic releases based on commits
Fixes #117
> ci: add semantic release

- .circleci/config.yml
Allows semantic release to use a github token
> ci: Use new honeydipper context

- .circleci/config.yml
- build/docker/Dockerfile
> fix(deps): Update to go 1.13.6

- .releaserc
> ci: Fix releaserc typo

- .releaserc
ci: Fix releaserc typo (#157)
n/a
> chore(release): release

- CHANGELOG.md
- Backfill CHANGELOG.md for previous releases
> docs: Backfill Changelog

- drivers/cmd/redispubsub/main.go
- drivers/cmd/redisqueue/main.go
- drivers/pkg/redisclient/redisclient.go
- internal/config/repo.go
- internal/workflow/continue.go
- pkg/dipper/mapUtils.go
- This PR will refactor duplicated code in a few places into common functions
> refactor: move duplicated code into common function

- cmd/honeydipper/configcheck_test.go
* add unit test for configcheck command
> test: add unit tests for configcheck

- cmd/honeydipper/configcheck.go
* add configcheck for the contexts section of honeydipper configurations
Fixes #211 
simple init file
```yaml
repos:
- repo: https://github.com/huydinhle/honeydipper-config-essentials.git
drivers:
redisqueue:
connection:
Addr: 127.0.0.1:6379
redispubsub:
connection:
Addr: 127.0.0.1:6379 
contexts:
two-tap-deploys:
notify:
notify+:
- '#two-tap-deploys'
huy-test:
break-it:
```
```
❯ REPO=. BRANCH=master LOCALREDIS=1 DEBUG='*' CHECK_REMOTE=1 honeydipper configcheck
Found error in Contexts
─────────────────────────────────────────────────────────────
context(huy-test): workflow `break-it` not defined
```
> feat: add contexts configcheck

- drivers/cmd/kubernetes/main.go
This is in addition to being able to recycle k8s deployment by label selector
Fixes #223
> feat(drivers): recycle k8s deployment by name

- .codefresh/honeydipper-manually.yml
- .codefresh/honeydipper-nightly.yml
- .codefresh/honeydipper-release.yml
- .codefresh/honeydipper-sphinx.yml
* add codefresh workflows to repo, to track changes
Fixes #138
> ci: add codefresh workflows #138

- README.md
- docs/README.md
Add links to the website and the docs site.
> docs: add links to website and readthedocs site

- .circleci/config.yml
- .dependency_decisions.yml
Adding a step to verify that only dependencies with approved licenses are used.
> ci: checking dependency licenses

- drivers/cmd/kubernetes/main.go
After adding the function, we still need to modify the `run_kubernetes` workflow to use this function in a `on_success` hook.
Partially Fixes #238
> feat(k8s): add a function for deleting jobs

- drivers/cmd/kubernetes/main.go
The correct way of calling the `watch` API is to first make a `list` call
then use the `ResourceVersion` as a starting point to stream the events.
Also, the API client credential may need re-authentication for longer
watching processes.
The existing `waitForJob` method lacks the two things, wrongly assuming
that a single `watch` call will handle the whole watching process. We
get errors like
* Not handling `nil` `evt.Object` (end of a watch call)
* Getting code `410 Gone` due to old `ResourceVersion`
* Auth errors due to expired credential
This commit fixes all these.
The preferred way of handling waiting is to use `informer` APIs. An
attempt has beenn made in PR #296, but unfortunately it has to be
abandoned for now due to some shortcomings. We will probably re-visit
the `informer` API …
> fix(drivers): watch API requries calling get and re-authentication

- drivers/cmd/auth-simple/main.go
- drivers/cmd/webhook/main.go
- internal/api/store.go
A few adjustments before release
* more strict ACL, deny be default
* encryption in handling password and token for web auth
* webhook silent response for backward compatibility
N/A
> fix: api auth and webhook adjustments

- internal/api/response_test.go
The old way of using `bytes.Buffer` to mock the `eventbus` doesn't block
when there is no data available, the test code has to have a logic to
loop and check to wait for the messages, thus creating timing issue. The
new way of using `io.Pipe` mimics the actual `eventbus` behavior in blocking.
* switching to `io.Pipe`
* increasing the allowed delay for waiting
N/A
> test(api): using io.Pipe to mock eventbus

- drivers/cmd/auth-simple/main.go
- internal/api/def.go
- internal/api/mock_api/request_context.go
- internal/api/store.go
- internal/service/api.go
- internal/service/service.go
- pkg/dipper/mock_dipper/rpc.go
* fix(drivers): auth-simple handling authorization header
* feat(api): healthcheck and configurable prefix
* test: some gofumpt changes
N/A
> feat(api): healthcheck and configurable prefix

- .circleci/config.yml
- .codefresh/honeydipper-release.yml
- .codefresh/honeydipper-sphinx.yml
- .github/semantic.yml
- .releaserc
* releases from main branch
* codefresh
* circleci
* honeydipper-sphinx
N/A
> chore: rename the master branch to main

- drivers/cmd/redislock/main.go
- drivers/cmd/redispubsub/main.go
- drivers/cmd/redisqueue/main.go
- drivers/pkg/redisclient/redisclient.go
- internal/service/service.go
- pkg/dipper/certs.go
- pkg/dipper/certs_test.go
- pkg/dipper/condition.go
- pkg/dipper/condition_test.go
- pkg/dipper/driver.go
- pkg/dipper/encryption.go
- pkg/dipper/encryption_test.go
- pkg/dipper/mapUtils.go
- pkg/dipper/mapUtils_test.go
* test(dipper): adding tests for DecryptAll
* feat(dipper): support deferred decryption in drivers
* feat(dipper): helper function to check truthy value
* feat(drivers): redis drivers support TLS
* fix(drivers): redis drivers avoid printing password
N/A
> fix(drivers): redis driver avoid printing password and support TLS

- internal/config/config.go
Each repo in config keeps its own raw DataSet besides the final
assembled DataSet. When changes are detetcted, new and unchanged repo
DataSets are used for re-assembling the updated final DataSet. Some of
the changes that made to the final assembled DataSet spills into the raw
repo DataSet, and makes it unsuitable for reuse, and in turn causes
re-assembling to crash during reload. To fix this,
- Make deep copies to avoid contaminating the original copy
- Adjust the locking and reload detection in AdvanceStage
Fixes #392
> fix(config): contaminated dataset crashes during reload

- drivers/cmd/gcloud-secret/main.go
- drivers/cmd/gcloud-secret/main_test.go
- internal/service/operator.go
* feat(drivers): gcloud-secret support shorthand key name
* feat(operator): support deferred decryption and lookup
Fixes #395
Fixes #388
> feat: betterment of secret handling

- internal/service/engine_apis.go
- internal/workflow/continue.go
- internal/workflow/session.go
- internal/workflow/store.go
This is useful when listing all in-fly workflows through api.
N/A
> feat(workflow): keep track of start and completion time

- .gitignore
- Makefile
- build/docker/Dockerfile
- build/docker/Dockerfile-dev
- dev/linux/docker-compose.pre-built.yaml
- dev/linux/docker-compose.yaml
- dev/macos/docker-compose.pre-built.yaml
- dev/macos/docker-compose.yaml
- docs/howtos/setup_local.md
Improve developer experiences using `docker-compose` and `Makefile`.
N/A
> chore: support running through docker-compose and Makefile

- drivers/cmd/webhook/main.go
- drivers/cmd/webhook/main_test.go
- internal/config/collapsed_trigger.go
- pkg/dipper/web.go
Support webhook header signature validation for github, slack and
pagerduty.
Fixes #389
> feat(drivers): webhook verify signature using hmac

- .circleci/config.yml
- Makefile
report test-coverage to codeclimate.
> ci: add codeclimate test coverage reporting

- .circleci/config.yml
use wget to get codeclimate test reporter
> ci: use wget to get codeclimate test reporter

- drivers/cmd/webhook/main.go
- drivers/cmd/webhook/main_test.go
Some systems such as pagerduty needs to have multiple secrets.
> feat(drivers): webhook hmac support secret list

- drivers/cmd/kubernetes/main.go
This allows creating a k8s job based on a cronjob definition, similar to `kubectl` with `--from=cronjob/name`.
N/A
> feat(drivers): create k8s job from cronjob spec

- internal/config/config.go
- internal/config/config_test.go
- internal/config/repo.go
Allowing override a repo with a directory is useful when running tests and config checks.
N/A
> feat(core): allow override a repo with a directory

- internal/config/repo.go
Should load the specified branch if specified.
> fix(core): refresh repo should load correct ref

- cmd/honeydipper/integration_test.go
- internal/api/response.go
- internal/api/response_test.go
- internal/driver/builtin.go
- internal/driver/builtin_test.go
- internal/driver/driver.go
- internal/driver/driver_test.go
- internal/driver/nulldriver.go
- internal/service/engine.go
- internal/service/operator.go
- internal/service/service.go
- internal/service/service_test.go
- pkg/dipper/comm.go
- pkg/dipper/driver.go
- pkg/dipper/encryption_test.go
- pkg/dipper/mock_dipper/rpc.go
- pkg/dipper/rpc.go
- pkg/dipper/rpc_test.go
Make comm API and driver API abstract for future extensibility and test-ability.
N/A
> refactor: abstract comm I/O with MessageReceiver 

- drivers/cmd/gcloud-logging/main.go
allow config multiple logger_name and projects in gcloud-logging
N/A
> fix: allow config multiple loggerName and projects in gcloud-logging

- internal/config/repo.go
The {% %} go template now supports using `.local.filename`. This is useful to extract org information from the file name and path.
> feat: local variables in go templates

- drivers/cmd/gcloud-storage/main.go
gcloud storage writeFile and getAttrs function
> feat: gcloud storage writeFile and getAttrs function

- drivers/cmd/gcloud-storage/main.go
* NewWriter doesn't return err object
* project is only needed for listBuckets
* file exists when err == nil
> fix: gcs driver various fixes

- .circleci/config.yml
Debug flag should be `get-commits` instead of `git-commits`
> ci: debug get-commits for issue with 123 124

- .github/workflows/check-semantic-commits.yml
- configs/sample-init.yaml
- docs/configuration.md
- docs/howtos/reload_on_push.md
- internal/config/repo.go
Switch to `main` vs `master` as default branch.
Note: I didn't flag this as breaking, though it technically is.
Also update allowed semantic commit types
Fixes #490
> feat(config): use main as default git branch

- cmd/honeydipper/main.go
- internal/config/config.go
- internal/config/repo.go
- internal/config/schema.go
- internal/service/engine.go
- internal/service/service.go
- internal/workflow/store.go
Allow running the honeydipper daemon in job mode. Meaning it will load a file specified by `JOB_FILE` run a workflow named `reserved/main` and quit once complete. Useful for test/debug locally. Will add the document for this in a separate PR.
Also fix: use main branch by default
In addition to #590, a few more places need to change to allow using main as default branch.
> feat: cli job mode

- .circleci/config.yml
> ci: upgrade node version for semantic-release
